name: force_update_example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  package_info_plus: ^5.0.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
